### ISSUE TITLE
CRA appears to disallow tsconfig compilerOptions.paths

### ISSUE THREAD

**Issue by devinrhode2** [risenforces/craco-alias#5] opened 2020-01-02 22:28 UTC
It also appears to disallow changing isolatedModules, but that's unrelated. CRA forces certain tsconfig options to be set, even if you change them in tsconfig, cra will override whatever you did (I believe to prevent some issues those settings would cause)

So I will not use aliases, as I'm more interested in using typescript

We could use lerna and create packages, or just npm install a package folder `npm install ./packages/my-package` where my-package folder contains a package.json file

**Comment by devinrhode2** [comment] 2020-01-02 22:36
CRA clearly prints out in the terminal that is is changing these options when running npm start.

**Comment by risenforces** [comment] 2020-01-03 00:19
@devinrhode2 Are you trying to specify these options directly in `tsconfig.json`? If so, you should create separate file (for example `tsconfig.edit.json`) and extend the main config from it.

Like that:
```js
// tsconfig.json

{
  "extends": "./tsconfig.edit.json",
  ...
}

// tsconfig.edit.json

{
  "compilerOptions": {
    "baseUrl": "src", 
    "paths": {
      "@file-alias": ["./your/file.tsx"],
      "@folder-alias/*": ["./very/long/path/*", "./very/long/path/"]
    }
  }
}
```

**Comment by devinrhode2** [comment] 2020-01-03 13:24
yep, followed the documentation... I am using latest version of
react-scripts, 3.3.0

**Comment by risenforces** [comment] 2020-01-03 20:37
@devinrhode2 Just checked. Yes, there really is such a problem. I’ll try to figure out if there is an opportunity to do something with this in order to leave everything as it is. `tsconfig` without paths setting makes vscode to not understand aliases correctly, it's very bad.

**Comment by risenforces** [comment] 2020-01-03 20:41
Currently you can specify aliases manually using the `config` source, but, as i said above, I'm not sure VSCode and some other editors and IDEs will know aliases without proper `tsconfig` options. I think WebStorm has an option to specify aliases somewhere in the settings, but anyway it's bad.

**Comment by devinrhode2** [comment] 2020-01-04 04:37
could consider using symlinks, or doing whatever lerna does, or just recommending some other method of creating aliases

**Comment by risenforces** [comment] 2020-01-04 11:04
Wait. I think everything should work as intended. `craco-alias` generates aliases and the CRA error means nothing for it. Using the separate tsconfig file disallows CRA to delete options from there. So VSCode and other editors still continue to suggest import paths, auto-imports and so.

I will check it again soon and close the issue if there is no problem.

In addition, I think readme part about tsconfig should be updated to be more convenient for understanding. I will edit it soon.

**Comment by risenforces** [comment] 2020-01-04 11:14
But anyway, if you want to use `isolatedModules` and other ts features, I don't think CRA is the best option. It really restricts config editing.

**Closed** 2020-01-05 19:44 UTC

**Comment by axetroy** [comment] 2020-08-21 07:09
> @devinrhode2 Are you trying to specify these options directly in `tsconfig.json`? If so, you should create a separate file (for example named `tsconfig.edit.json`) and extend the main config from it.
> 
> Like that:
> 
> ```js
> // tsconfig.json
> 
> {
>   "extends": "./tsconfig.edit.json",
>   ...
> }
> 
> // tsconfig.edit.json
> 
> {
>   "compilerOptions": {
>     "baseUrl": "src", 
>     "paths": {
>       "@file-alias": ["./your/file.tsx"],
>       "@folder-alias/*": ["./very/long/path/*", "./very/long/path/"]
>     }
>   }
> }
> ```

I tried this solution and it is well recognized in the IDE/editor but doesn't work for craco

**Comment by antonlashan** [comment] 2020-11-27 12:22
@axetroy override webpack config in craco.config
```js
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  plugins: [
    ...
    {
      plugin: {
        overrideWebpackConfig: ({ webpackConfig }) => {
          webpackConfig.resolve.plugins.push(new TsconfigPathsPlugin({}));
          return webpackConfig;
        }
      },
    }
  ],
};
```
